export enum SETTINGS_ACTION_TYPES {
    SET_SELECT_AREA_MODE = "settings/SET_SELECT_AREA_MODE",
    SET_SELECTED_WEATHER_FIELD = "settings/SET_SELECTED_WEATHER_FIELD",
    SET_SELECTED_DATE_ID = "settings/SET_SELECTED_DATE_ID",
    SET_LOADING = "settings/SET_LOADING",
    SET_IS_SIDEBAR_OPEN = "settings/SET_IS_SIDEBAR_OPEN",
    FETCH_WEATHER_FIELDS_SUCCESS = "settings/FETCH_WEATHER_FIELDS_SUCCESS",
    FETCH_WEATHER_FIELDS_FAILED = "settings/FETCH_WEATHER_FIELDS_FAILED",
    FETCH_WEATHER_DATES_SUCCESS = "settings/FETCH_WEATHER_DATES_SUCCESS",
    FETCH_WEATHER_DATES_FAILED = "settings/FETCH_WEATHER_DATES_FAILED",
    SET_ERROR_MESSAGE = "settings/SET_ERROR_MESSAGE",
    SET_INFO_MESSAGE = "settings/SET_INFO_MESSAGE",
    SET_SUCCESS_MESSAGE = "settings/SET_SUCCESS_MESSAGE"
};