export enum MAP_ACTION_TYPES {
    SET_COMPARED_FEATURES = "map/SET_COMPARED_FEATURES",
    SET_HOVERED_FEATURE = "map/SET_HOVERED_FEATURE",
    SET_SELECTED_FEATURE = "map/SET_SELECTED_FEATURE",
    SET_GEOJSON_DATA = "map/SET_GEOJSON_DATA",
    SET_WEATHER_ALERTS = "map/SET_WEATHER_ALERTS",
    SET_NEXT_LAYER = "map/SET_NEXT_LAYER"
};