export enum USER_ACTION_TYPES {
    SIGN_IN_SUCCESS = "user/SIGN_IN_SUCCESS",
    SIGN_IN_FAILED = "user/SIGN_IN_FAILED",
    SIGN_UP_FAILED = "user/SIGN_UP_FAILED",
    SIGN_OUT_SUCCESS = "user/SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILED = "user/SIGN_OUT_FAILED",
    SET_USER_LOCATIONS_SUCCESS = "user/SET_USER_LOCATIONS_SUCCESS",
    SET_USER_LOCATIONS_FAILED = "user/SET_USER_LOCATIONS_FAILED",
    SET_WEATHER_ALERTS = "user/SET_WEATHER_ALERTS"
};